apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./mariadb
  - ./nginx-unprivileged
  - ingress.yaml
  - service.yaml
  - serviceaccount.yaml

commonLabels:
  app: corgi
  app.kubernetes.io/name: corgi

# Teach kustomize how to update generated names
#
configurations:
  - kustomizeconfig.yaml

patches:
  # Remove default kustomize-generated secret from base
  #
  - target:
      name: mariadb-credentials
      kind: Secret
    patch: |
      $patch: delete
      kind: Kustomization
      metadata:
        name: DOES NOT MATTER

  # Remove conflicting nginx-unprivileged update strategy
  #
  - target:
      kind: Deployment
    patch: |-
      - op: remove
        path: /spec/strategy/rollingUpdate

  # Remove nginx-unprivileged from base name
  #
  - path: deployment.yaml
    target:
      kind: Deployment
    options:
      allowNameChange: true

  # Update statefulset to use secrets retrieved from Vault
  #
  - path: statefulset-patch.yaml
    target:
      kind: StatefulSet

  # Remove base envs
  #
  - target:
      kind: StatefulSet
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env

configMapGenerator:
  # AWS env var config
  #
  - name: aws-config
    literals:
      - AWS_BUCKET=corgi-bucket-2020-06-02
      - AWS_DB_BACKUP=corgi-db-backup
      - AWS_CLOUDFRONT_URL=https://d15c7x5l8vffhv.cloudfront.net
      - AWS_CLOUDFRONT_ID=E1P1B7ZVPWOOPU
      - ENABLE_AWS_STORAGE=true

  # BCIT LDAP env var config
  #
  - name: ldap-config
    literals:
      - LDAP_LOGGING=true
      - LDAP_BASE_DN="DC=ad,DC=bcit,DC=ca"
      - LDAP_SYNC_ADMIN_PROGRAMS_ON_EACH_REQUEST=false
      - LDAP_HOSTS="ldaps.ad.bcit.ca"

  # Sets mariadb db
  #
  - name: mariadb-config
    literals:
      - MARIADB_DATABASE=corgi
      - TZ=America/Vancouver

  # Generates elasticapm initial config
  #
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com

components:
  - ./components/conf.d
  - ./components/init.d
