# yaml-language-server: disable
apiVersion: v1
kind: ResourceQuota
metadata:
  name: hriv-restore-validation
  labels:
    {{- include "hriv-restore-validation.labels" . | nindent 4 }}
spec:
  hard:
    count/jobs.batch: "32"
    count/pods: "40"
    count/services: "16"
    count/configmaps: "16"
    count/persistentvolumeclaims: "8"
    count/clusters.postgresql.cnpg.io: "3"
    requests.cpu: "12"
    requests.memory: 6Gi
    requests.storage: 320Gi
    limits.cpu: "24"
    limits.memory: 8Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: hriv-restore-validation
  labels:
    {{- include "hriv-restore-validation.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      min:
        cpu: 10m
        memory: 16Mi
      max:
        cpu: "4"
        memory: 8Gi
    - type: PersistentVolumeClaim
      min:
        storage: 1Gi
      max:
        storage: 200Gi
