{{- include "hriv-restore-validation.validate" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hriv-restore-validation-orchestrator
  labels:
    {{- include "hriv-restore-validation.labels" . | nindent 4 }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hriv-restore-validation-no-permission
  labels:
    {{- include "hriv-restore-validation.labels" . | nindent 4 }}
automountServiceAccountToken: false
