{{- if .Values.backend.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "corgi.fullname" . }}-image-data
  labels:
    {{- include "corgi.labels" . | nindent 4 }}
    {{- include "corgi.backend.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
{{- end }}
