---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  name: config-component


# Generates ConfigMap resources to adjust/create base values
#
configMapGenerator:
  - name: aws-cli-config
    files:
      - ./aws/cli-config.ini
  - name: imagemagick-config
    files:
      - ./ImageMagick/policy.xml
  - name: nginx-config
    files:
      - ./nginx/default.conf
    behavior: replace
  - name: phpfpm-config
    files:
      - ./php/corgi.conf
  - name: phpini-config
    files:
      # - ./php/conf.d/local.ini/local.ini
      - ./php/conf.d/uploads.ini
  - name: supervisor-config
    files:
      - ./supervisor/supervisord.conf
