[global]
; default=0
emergency_restart_threshold = 10

; default=0
emergency_restart_interval = 1m

; default=0
process_control_timeout = 10s

[www]
; default=0 (unlimited)
pm.max_requests = 200

; default=/var/run/php-fpm.sock
listen = 9000
