---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component


# Generates ConfigMap resources to adjust/create base values
#
configMapGenerator:
  - name: db-init.sh
    files:
      - ./db-init.sh
