# adds secrets to deployment
#   - nginx-unprivileged is container=0
---
- op: add
  path: /spec/template/spec/containers/1/envFrom/-
  value:
    secretRef:
      name: aws-credentials

- op: add
  path: /spec/template/spec/containers/1/envFrom/-
  value:
    secretRef:
      name: elastic-apm-token

- op: add
  path: /spec/template/spec/containers/1/envFrom/-
  value:
    secretRef:
      name: ldap-credentials

- op: add
  path: /spec/template/spec/containers/1/envFrom/-
  value:
    secretRef:
      name: mariadb-credentials
