apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  environment: latest
# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: corgi-
nameSuffix: -latest
# Facilitate kustomization name updating
#
configurations:
  - kustomizeconfig.yaml
commonAnnotations:
  version: 1.2.8-6b312a67--2023-10-07.1696656463 # {"$imagepolicy": "corgi:corgi-image-policy-latest:tag"}
images:
  - name: "corgi"
    newName: "registry.ltc.bcit.ca/web-apps/corgi/corgi"
    newTag: "1.2.8-6b312a67--2023-10-07.1696656463" # {"$imagepolicy": "corgi:corgi-image-policy-latest:tag"}
patches:
  # Patches ingress with "latest--"
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  # Adds secrets to deployment
  - target:
      kind: Deployment
    path: deployment-patch.yaml
  # Adds secrets to statefulset
  - target:
      kind: StatefulSet
    path: statefulset-patch.yaml
  # Incorporate vault-secrets
  #
  # adds `-latest` suffix to VaultAuth `spec.mount`
  - target:
      kind: VaultAuth
    path: vault-secrets-latest/vault-auth-patch.yaml
components:
  # Include environment-specific secrets
  - ./vault-secrets-latest
  # Required for VaultAuth role and serviceaccounts
  - ../../base/components/vault-auth
configMapGenerator:
  # Updates elasticapm config
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=corgi-latest
    behavior: merge
  # Updates nginx config with overlay-specific `fastcgi_pass` service name
  - name: nginx-config
    files:
      - conf.d/nginx/default.conf
    behavior: replace
  # Can switch to testing bucket for images
  #
  - name: aws-config
    literals:
      - AWS_BUCKET=corgi-test-bucket-2020-06-29
    behavior: merge