[supervisord]
user=root
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

# create image queue
[program:laravel-worker-createImageQueue]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /corgi/artisan queue:work database --queue=createImageQueue --sleep=3 --tries=3
user=www-data
autostart=true
autorestart=true
numprocs=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

# delete image queue
[program:laravel-worker-deleteImageQueue]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /corgi/artisan queue:work database --queue=deleteImageQueue --sleep=3 --tries=3
user=www-data
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-fpm]
process_name=%(program_name)s_%(process_num)02d
command = /usr/local/sbin/php-fpm
autostart=true
autorestart=true
priority=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
numprocs=1
# redirect_stderr=true
