{{- if .Values.versionConfigMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.versionConfigMap.name }}
  labels:
    {{- include "hriv-frontend.labels" . | nindent 4 }}
data:
  {{ .Values.versionConfigMap.key }}: {{ include "hriv-frontend.displayVersion" . | quote }}
  {{ .Values.versionConfigMap.imageTagKey }}: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
{{- end }}
