apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alt-ingress
spec:
  tls:
    - hosts:
        - stable--corgi.ltc.bcit.ca
      secretName: star-ltc-bcit-ca
  rules:
    # Alt URL `stable--` to confirm deployment until DNS is updated
    #
    - host: stable--corgi.ltc.bcit.ca
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: corgi-nginx-service
                port:
                  number: 80
