---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-db-backup
spec:
  # Run every 3 hours
  #
  schedule: "0 */3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: corgi-serviceaccount
          containers:
          - name: mariadb-db-backup
            image: mariadb
            env:
            # Limit backup access to read-only service
            #
            # - name: MARIADB_ROOT_HOST
            #   value: corgi-mariadb-read-service
            envFrom:
            - configMapRef:
                name: aws-config
            - configMapRef:
                name: mariadb-config
            - secretRef:
                name: aws-credentials
            - secretRef:
                name: mariadb-credentials
            command:
            - /bin/sh
            - -c
            - |
              # Create backup and store on AWS S3
              #   - required env vars: AWS_BUCKET, AWS_DB_BACKUP, 
              #     AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION
              #     MARIADB_USER, MARIADB_PASSWORD, MARIADB_DATABASE


              # Install dependencies
              #
              apt-get update
              apt-get install -y curl unzip jq
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip && ./aws/install


              # Confirm env vars
              #
              echo "AWS_BUCKET: $AWS_BUCKET"
              echo "AWS_DB_BACKUP: $AWS_DB_BACKUP"
              echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
              echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
              echo "MARIADB_ROOT_HOST: $MARIADB_ROOT_HOST"
              echo "MARIADB_USER: $MARIADB_USER"
              echo "MARIADB_PASSWORD: $MARIADB_PASSWORD"
              echo "MARIADB_DATABASE: $MARIADB_DATABASE"


              # Confirm mariadb connection and that service is up
              #
              mariadb-admin -h$MARIADB_ROOT_HOST -u$MARIADB_USER -p$MARIADB_PASSWORD ping
              

              # Create db dump
              #
              mariadb-dump -h$MARIADB_ROOT_HOST -u$MARIADB_USER -p$MARIADB_PASSWORD --databases $MARIADB_DATABASE > /tmp/dump.sql


              # Upload to S3
              #   - file format: YYYY-MM-DD_HH-MM.sql
              #
              aws s3 cp /tmp/dump.sql s3://$AWS_BUCKET/$AWS_DB_BACKUP/$(date +%Y-%m-%d_%H-%M).sql


              # Cleanup
              #
              rm /tmp/dump.sql

          restartPolicy: OnFailure
