---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: aws-credentials
spec:
  vaultAuthRef: vault-auth
  refreshAfter: 6h
  mount: aws
  path: stable-s3-full-access
  destination:
    create: true
    name: aws-credentials
