---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  # - aws-dynamic-credentials.yaml
  - aws-static-credentials.yaml
  - elastic-apm-token.yaml
  - ldap-credentials.yaml
  - mariadb-credentials.yaml
  - star-ltc-bcit-ca.yaml
