apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mariadb-credentials
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  refreshAfter: 6h
  mount: apps
  path: corgi/stable/mariadb-credentials
  destination:
    name: mariadb-credentials
    create: true
