"""Add tile-cache provenance columns to source_images.

Records enough provenance to evaluate whether a generated tile tree is
``current`` / ``missing`` / ``stale`` / ``failed`` after a restore, source
replacement, or tile-generation pipeline change (issue #734) without manual
filesystem inspection.

- ``source_checksum``: SHA-256 of the source file used to generate the tiles.
- ``tile_settings_hash``: fingerprint of the tile-generation settings/version.
- ``tiles_generated_at``: timestamp tiles were last generated.

All columns are nullable. Already-``completed`` source images are backfilled so
their tiles (generated by the only pipeline version that has ever existed, v1)
report as ``current`` rather than ``missing`` — see the backfill below. Rows in
any other state are left untouched: a row with no ``tiles_generated_at``
evaluates as ``missing`` (or ``failed`` when its processing status is
``failed``). The effective ``tile_cache_status`` is computed at read time and
intentionally not stored, so it can never drift from the current settings hash.

Revision ID: 0014_add_tile_provenance
Revises: 0013_alter_note_to_text
Create Date: 2026-06-23
"""

from alembic import op
import sqlalchemy as sa

revision = "0014_add_tile_provenance"
down_revision = "0013_alter_note_to_text"
branch_labels = None
depends_on = None

# SHA-256 of the v1 tile-generation settings
# ("v=1|tile_size=254|overlap=1|suffix=.jpeg[Q=85]"). Hardcoded so this
# migration's backfill stays deterministic and independent of app code; it
# matches ``app.tile_provenance.current_tile_settings_hash()`` while
# ``TILE_GENERATION_VERSION == 1``.
_V1_TILE_SETTINGS_HASH = (
    "60d0d2d69b3dbe1fe4af0f7318b771da937f8743822710339fd1fe97413d082f"
)


def upgrade() -> None:
    op.add_column(
        "source_images",
        sa.Column("source_checksum", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "source_images",
        sa.Column("tile_settings_hash", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "source_images",
        sa.Column("tiles_generated_at", sa.DateTime(timezone=True), nullable=True),
    )

    # Backfill provenance for source images that already completed before this
    # migration. Their tiles exist on disk (a ``completed`` status has always
    # implied a generated tile tree) and were produced by the v1 pipeline, so
    # mark them ``current`` instead of leaving them to evaluate as ``missing``.
    # ``source_checksum`` is intentionally left NULL — it can't be recomputed
    # here without reading source files, and it isn't used for status.
    op.execute(
        sa.text(
            """
            UPDATE source_images
            SET tiles_generated_at = updated_at,
                tile_settings_hash = :v1_hash
            WHERE status = 'completed'
              AND tiles_generated_at IS NULL
            """
        ).bindparams(v1_hash=_V1_TILE_SETTINGS_HASH)
    )


def downgrade() -> None:
    op.drop_column("source_images", "tiles_generated_at")
    op.drop_column("source_images", "tile_settings_hash")
    op.drop_column("source_images", "source_checksum")
