{{- if and .Values.persistence.enabled (not .Values.persistence.sourceImages.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-source-images" (include "hriv-backend.fullname" .) }}
  labels:
    {{- include "hriv-backend.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.sourceImages.storageClass }}
  storageClassName: {{ .Values.persistence.sourceImages.storageClass }}
  {{- end }}
  accessModes:
    {{- range .Values.persistence.sourceImages.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.sourceImages.size }}
{{- end }}
---
{{- if and .Values.persistence.enabled (not .Values.persistence.tilesPersistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-tiles" (include "hriv-backend.fullname" .) }}
  labels:
    {{- include "hriv-backend.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.tilesPersistence.storageClass }}
  storageClassName: {{ .Values.persistence.tilesPersistence.storageClass }}
  {{- end }}
  accessModes:
    {{- range .Values.persistence.tilesPersistence.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.tilesPersistence.size }}
{{- end }}
