{{- if not .Values.vault.enabled }}
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hriv-backend.fullname" . }}-db-superuser-bootstrap
  labels:
    {{- include "hriv-backend.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ .Values.postgres.auth.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hriv-backend.fullname" . }}-db-bootstrap
  labels:
    {{- include "hriv-backend.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
{{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hriv-backend.fullname" . }}-db-app
type: Opaque
stringData:
  {{- if .Values.postgres.enabled }}
  uri: "postgresql://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ include "hriv-backend.fullname" . }}-db-rw:5432/{{ .Values.postgres.auth.database }}"
  {{- else if .Values.postgres.uri }}
  uri: {{ .Values.postgres.uri | quote }}
  {{- else }}
  {{- fail "postgres.enabled=false without vault.enabled=true requires postgres.uri" }}
  {{- end }}
{{- end }}
