{{- if not .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corgi-backend.fullname" . }}-db-superuser-bootstrap
  labels:
    {{- include "corgi-backend.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ .Values.cnpg.devPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corgi-backend.fullname" . }}-db-bootstrap
  labels:
    {{- include "corgi-backend.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cnpg.owner | quote }}
  password: {{ .Values.cnpg.devPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corgi-backend.fullname" . }}-github-pat
  labels:
    {{- include "corgi-backend.labels" . | nindent 4 }}
type: Opaque
# data: keys must be base64-encoded
stringData:
  token: someGHtoken
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corgi-backend.fullname" . }}-db-app
type: Opaque
stringData:
  uri: "postgresql://{{ .Values.cnpg.owner }}:{{ .Values.cnpg.devPassword }}@{{ include "corgi-backend.fullname" . }}-db-rw:5432/{{ .Values.cnpg.database }}"
{{- end }}
