{{- if and .Values.oidc.enabled (not .Values.vault.enabled) (not .Values.oidc.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hriv-backend.fullname" . }}-oidc
  labels:
    {{- include "hriv-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-id: {{ .Values.oidc.clientId | quote }}
  client-secret: {{ .Values.oidc.clientSecret | quote }}
{{- end }}
