apiVersion: v1
kind: Service
metadata:
  name: {{ include "hriv-backend.fullname" . }}
  labels:
    {{- include "hriv-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.tileSidecar.enabled }}
    - port: {{ .Values.tileSidecar.port }}
      targetPort: tiles
      protocol: TCP
      name: tiles
    {{- end }}
  selector:
    {{- include "hriv-backend.selectorLabels" . | nindent 4 }}
