apiVersion: v1
kind: Service
metadata: # kpt-merge: /service
  name: service
  labels:
    tier: mariadb
    app.kubernetes.io/name: mariadb
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|default|service'
spec:
  ports:
    - name: mariadb
      port: 3306
  selector:
    tier: mariadb
  clusterIP: None
