apiVersion: v2
name: hriv-backup
description: HRIV Backup Service – scheduled database and filesystem snapshots
type: application
version: 0.12.0 # x-release-please-version
appVersion: '0.12.0' # x-release-please-version
