"""Shared task timing constants."""

WORKER_JOB_TIMEOUT_SECONDS = 7200
SOURCE_IMAGE_PENDING_WAIT_SAFETY_CAP_SECONDS = max(
    WORKER_JOB_TIMEOUT_SECONDS // 2,
    1,
)
BULK_IMPORT_COORDINATOR_LIVENESS_KEY = "hriv:bulk_import:coordinators"
BULK_IMPORT_COORDINATOR_LIVENESS_WINDOW_SECONDS = 90
