apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: aws-credentials
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  refreshAfter: 6h
  mount: ltc-infrastructure
  path: aws-credentials/latest/aws-credentials
  # path: aws-credentials/latest/s3-credentials
  destination:
    name: aws-credentials
    create: true
