apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ldap-credentials
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  refreshAfter: 6h
  mount: ltc-infrastructure
  path: bcit-active-directory/latest/ldap-credentials
  destination:
    name: ldap-credentials
    create: true
