{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "corgi-backup.fullname" . }}-data
  labels:
    {{- include "corgi-backup.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.data.storageClass }}
  accessModes:
    {{- range .Values.persistence.data.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
---
{{- if .Values.persistence.backups.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "corgi-backup.fullname" . }}-backups
  labels:
    {{- include "corgi-backup.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.backups.storageClass }}
  accessModes:
    {{- range .Values.persistence.backups.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.size }}
{{- end }}
