{{- if and .Values.persistence.sourceImages.enabled (not .Values.persistence.sourceImages.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hriv-backup.fullname" . }}-source-images
  labels:
    {{- include "hriv-backup.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.sourceImages.storageClass }}
  storageClassName: {{ .Values.persistence.sourceImages.storageClass }}
  {{- end }}
  accessModes:
    {{- range .Values.persistence.sourceImages.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.sourceImages.size }}
{{- end }}
---
{{- if and .Values.persistence.tiles.enabled (not .Values.persistence.tiles.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hriv-backup.fullname" . }}-tiles
  labels:
    {{- include "hriv-backup.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.tiles.storageClass }}
  storageClassName: {{ .Values.persistence.tiles.storageClass }}
  {{- end }}
  accessModes:
    {{- range .Values.persistence.tiles.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.tiles.size }}
{{- end }}
---
{{- if .Values.persistence.backups.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hriv-backup.fullname" . }}-backups
  labels:
    {{- include "hriv-backup.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.backups.storageClass }}
  storageClassName: {{ .Values.persistence.backups.storageClass }}
  {{- end }}
  accessModes:
    {{- range .Values.persistence.backups.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.size }}
{{- end }}
