{{- if not .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corgi-backup.fullname" . }}-azure
  labels:
    {{- include "corgi-backend.labels" . | nindent 4 }}
type: Opaque
# data: keys must be base64-encoded
stringData:
  AZURE_STORAGE_CONNECTION_STRING: azureConnectionString
{{- end }}
