; default=2M
upload_max_filesize=4096M

; default=8M
post_max_size=6144M

; default=128M
memory_limit=8192M
file_uploads = On


; extensions
;extension=ldap.so
;extension=vips.so

; default=null for all
;php_flag[display_errors] = on
;php_admin_value[error_log] = /var/log/fpm-php.www.log
;php_admin_flag[log_errors] = on